### PR TITLE
compare two linked lists

### PR DESCRIPTION
**Pull request by Kushbankey**

### CODE REVIEW

**Comment by av1shek** [comment]
Please add this inside a folder from which platform it belongs to, also add problem code in filename and remove ".exe" file. For details please checkout guidelines in readme.

**Comment by av1shek** [comment]
Issue #88

**Comment by av1shek** [comment]
Remove ".exe" file also.

**Comment by Kushbankey** [comment]
".exe" file removed. Please review and approve the pull request.

**Pull request merged**
